spring:
  application:
    name: order-service
    
# server:
  # port: 8201

eureka:
  client:
    service-url:
      #defaultZone结合云服务器才能设置其它选项
           # 同时向eureka集群中的每台服务器都注册服务地址
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202